"""Generate the gettext POT template from Deluxe Sync Python source."""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass, field
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "DeluxeSync"
OUTPUT = SOURCE_DIR / "translations" / "messages.pot"


@dataclass
class Message:
    msgid: str
    msgid_plural: str | None = None
    references: set[str] = field(default_factory=set)


def call_name(node: ast.AST) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return ""


def string_literal(node: ast.AST) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def quote_po(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\t", "\\t")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    )
    return f'"{escaped}"'


def extract_messages() -> dict[tuple[str, str | None], Message]:
    messages: dict[tuple[str, str | None], Message] = {}

    for path in sorted(SOURCE_DIR.rglob("*.py")):
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(path))
        relative = path.relative_to(ROOT).as_posix()

        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue

            name = call_name(node.func)
            if name == "_" and node.args:
                msgid = string_literal(node.args[0])
                if msgid is None:
                    continue
                key = (msgid, None)
                message = messages.setdefault(key, Message(msgid=msgid))
                message.references.add(f"{relative}:{node.lineno}")
            elif name == "ngettext" and len(node.args) >= 2:
                singular = string_literal(node.args[0])
                plural = string_literal(node.args[1])
                if singular is None or plural is None:
                    continue
                key = (singular, plural)
                message = messages.setdefault(
                    key,
                    Message(msgid=singular, msgid_plural=plural),
                )
                message.references.add(f"{relative}:{node.lineno}")

    return messages


def render(messages: dict[tuple[str, str | None], Message]) -> str:
    lines = [
        '# Deluxe Sync translation template.',
        '# Generated by scripts/extract_translations.py; do not edit by hand.',
        'msgid ""',
        'msgstr ""',
        '"Project-Id-Version: Deluxe Sync\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        '"MIME-Version: 1.0\\n"',
        '"Plural-Forms: nplurals=2; plural=(n != 1);\\n"',
        "",
    ]

    for key in sorted(messages, key=lambda item: (item[0].casefold(), item[1] or "")):
        message = messages[key]
        refs = " ".join(sorted(message.references))
        lines.append(f"#: {refs}")
        lines.append(f"msgid {quote_po(message.msgid)}")
        if message.msgid_plural is None:
            lines.append('msgstr ""')
        else:
            lines.append(f"msgid_plural {quote_po(message.msgid_plural)}")
            lines.append('msgstr[0] ""')
            lines.append('msgstr[1] ""')
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if messages.pot is missing or out of date instead of rewriting it.",
    )
    args = parser.parse_args()

    messages = extract_messages()
    generated = render(messages)

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else None
        if current != generated:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date")
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is current ({len(messages)} messages)")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(messages)} messages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
